spring: 
 profiles: 
  active: 
  - dev

---
server: 
  port: 8001
  
mybatis: 
 config-location: classpath:mybatis/mybatis.cfg.xml
 type-aliases-package: com.ablf.springcloud.entities
 mapper-locations:
 - classpath:mybatis/mapper/**/*.xml

spring: 
 profiles: dev
 application: 
  name: microservicecloud-dept
 datasource: 
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: org.gjt.mm.mysql.Driver
  url: jdbc:mysql://47.104.226.241:3306/cloudDB02?useUnicode=true&characterEncoding=utf8
  username: root
  password: 111111!
  dbcp2: 
   min-idle: 5 
   initial-size: 5
   max-total: 5
   max-wait-millis: 200

eureka: 
 client: 
  service-url: 
   defaultZone: http://eureka7001:7001/eureka
 instance: 
  instance-id: microservicecloud-dept8001
  prefer-ip-address: true

  
---
server: 
  port: 8001
  
mybatis: 
 config-location: classpath:mybatis/mybatis.cfg.xml
 type-aliases-package: com.ablf.springcloud.entities
 mapper-locations: 
 - classpath:mybatis/mapper/**/*.xml

spring: 
 profiles: test
 application: 
  name: microservicecloud-dept
 datasource: 
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: org.gjt.mm.mysql.Driver
  url: jdbc:mysql://47.104.226.241:3306/cloudDB02?useUnicode=true&characterEncoding=utf8
  username: root
  password: 111111!
  dbcp2: 
   min-idle: 5
   initial-size: 5
   max-total: 5
   max-wait-millis: 200

eureka: 
 client: 
  service-url: 
   defaultZone: http://eureka7001:7001/eureka
 instance: 
  instance-id: microservicecloud-dept8001
  prefer-ip-address: true
  


  